
[window]
padding = { x = 8, y = 8 }
dynamic_padding = true
opacity = 0.95
decorations = "none"
dimensions = { columns = 100, lines = 30 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12.0

[colors.primary]
background = "#0f0f0f"
foreground = "#e5e5e5"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black   = "#1c1c1c"
red     = "#af5f5f"
green   = "#5f875f"
yellow  = "#87875f"
blue    = "#5f87af"
magenta = "#875f87"
cyan    = "#5f8787"
white   = "#e4e4e4"

[colors.bright]
black   = "#262626"
red     = "#ff5f5f"
green   = "#87af87"
yellow  = "#ffffaf"
blue    = "#87afd7"
magenta = "#d7afd7"
cyan    = "#87d7d7"
white   = "#ffffff"

[terminal]
shell = { program = "wsl", args = ["-d", "archlinux", "--cd", "~"] }

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
]
